#ifndef __ST2D_ERRCODE_H__
#define __ST2D_ERRCODE_H__

namespace st2dErrCode {

enum RENDERDEV {
	ST_ERR_CREATE_D3D9INTERFACE = -100,
	ST_ERR_GETDEVICECAPS		= -101,
	ST_ERR_GETDISPLAYMODE		= -102,
	ST_ERR_GETADAPTERINDENTIFIER = -103,
	ST_ERR_REINITALIZE			= -104,
	ST_ERR_ENUMADAPTERMODES		= -105,
	ST_ERR_RESET				= -106
};

enum WINDOW {
	ST_ERR_REGISTERCLASS		= -107,
	ST_ERR_CREATEWINDOW			= -108,
	ST_ERR_SETTOPMOST			= -109
};

enum GRAPHICS {
	ST_ERR_RENDERBEGIN			= -110,
	ST_ERR_RENDEREND			= -111,
	ST_ERR_PRESENT				= -112,
	ST_ERR_TRVIEW				= -113,
	ST_ERR_TRPROJ				= -114,
	ST_ERR_TRWORLD				= -115,
};

}

#endif /* !__ST2D_ENUM_H__ */
